name: Rust test workflow
on:
  push:
    branches:
      - 'main' 
jobs:
  test-restore-build:
    name: Test restore compile and store
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Update APT package index
        run: sudo apt-get update
        
      - name: Install and download required APT packages
        run: sudo apt-get install -y rustup

      - name: Restore Cargo cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-restore-build

      - name: Write to target
        run: cargo build

      - name: Delete Previous Cache
        if: ${{ steps.cache-restore.outputs.cache-hit }}
        continue-on-error: true
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache delete "${{ runner.os }}-restore-build" --confirm
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Save Cargo cache
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-restore-build
