name: Rust test workflow
on:
  push:
    branches:
      - 'main' 
jobs:
  test-restore-build:
    name: Test restore compile and store
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Update APT package index
        run: sudo apt-get update
        
      - name: Install and download required APT packages
        run: sudo apt-get install -y rustup

      - name: Restore Cargo cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-restore-build

      - name: Write to target
        run: cargo build
